/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Client;

import Business.Network;
import Core.UserAccount;
import Core.WorkOrder;
import Core.WorkOrders.CrossEnterpriseWorkOrder;
import UserInterface.WorkArea.*;
import javax.swing.JPanel;

/**
 *
 * @author connorewart
 */
public class HiringManagerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorkAreaTemplatePanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Network network;
    private String currentRequestType = "Candidate Submission";
    public HiringManagerJPanel(JPanel userProcessContainer, UserAccount account, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.network = network;
        btnBack.setVisible(false);
        btnRefresh.addActionListener(event ->
                populateRequestTable(currentRequestType));
        btnReports.addActionListener(event -> showHiringSummary());
        populateRequestTable(currentRequestType);
    }
    public void setWorkAreaHeader(String title, String subtitle) {
        lblTitle.setText(title);
        lblSubtitle.setText(subtitle);
    }

    public void setButtonLabels(String viewText, String primaryText, String manageText, String reportsText) {
        btnViewRequests.setText(viewText);
        btnPrimaryAction.setText(primaryText);
        btnManageRecords.setText(manageText);
        btnReports.setText(reportsText);
    }

    public void clearTable() {
        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) tblMain.getModel();
        model.setRowCount(0);
    }

    public void showMessage(String message) {
        javax.swing.JOptionPane.showMessageDialog(this, message);
    }

    public void showError(String message) {
        javax.swing.JOptionPane.showMessageDialog(this, message, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        btnViewRequests = new javax.swing.JButton();
        btnManageRecords = new javax.swing.JButton();
        btnPrimaryAction = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();
        btnViewRequests1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        lblTitle.setFont(new java.awt.Font("Myanmar Sangam MN", 3, 18)); // NOI18N
        lblTitle.setText("HR Work Area");

        lblSubtitle.setFont(new java.awt.Font("Myanmar MN", 0, 13)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(102, 102, 102));
        lblSubtitle.setText("Client Enterprise - HR Organization");

        btnViewRequests.setText("View Candidates");
        btnViewRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestsActionPerformed(evt);
            }
        });

        btnManageRecords.setText("Manage Contractors");
        btnManageRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRecordsActionPerformed(evt);
            }
        });

        btnPrimaryAction.setText("Staffing Requests");
        btnPrimaryAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimaryActionActionPerformed(evt);
            }
        });

        btnBack.setText("Back");

        btnRefresh.setText("Refresh");

        btnReports.setText("Reports");

        tblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Type", "Status", "Sender", "Receiver", "Date"
            }
        ));
        jScrollPane1.setViewportView(tblMain);

        btnViewRequests1.setText("View Invoices");
        btnViewRequests1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequests1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblSubtitle)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnViewRequests)
                                            .addComponent(btnManageRecords)
                                            .addComponent(btnViewRequests1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnPrimaryAction)
                                            .addComponent(btnReports)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblTitle)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewRequests)
                    .addComponent(btnPrimaryAction))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewRequests1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReports)
                    .addComponent(btnManageRecords))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnRefresh))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestsActionPerformed
        HiringManagerCandidateApprovalJPanel panel = new HiringManagerCandidateApprovalJPanel(userProcessContainer, account, network);
        userProcessContainer.add("HiringManagerCandidateApprovalJPanel", panel);
        java.awt.CardLayout layout = (java.awt.CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewRequestsActionPerformed

    private void btnViewRequests1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequests1ActionPerformed
        HiringManagerInvoiceJPanel panel = new HiringManagerInvoiceJPanel(userProcessContainer, account, network);
        userProcessContainer.add("HiringManagerInvoiceJPanel", panel);
        java.awt.CardLayout layout = (java.awt.CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewRequests1ActionPerformed

    private void btnPrimaryActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimaryActionActionPerformed
        HiringManagerStaffingReqsJPanel panel = new HiringManagerStaffingReqsJPanel(userProcessContainer, account, network);
        userProcessContainer.add("HiringManagerStaffingReqsJPanel", panel);
        java.awt.CardLayout layout = (java.awt.CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPrimaryActionActionPerformed

    private void btnManageRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRecordsActionPerformed
        HiringManagerContractorsJPanel panel = new HiringManagerContractorsJPanel(userProcessContainer, account, network);
        userProcessContainer.add("HiringManagerContractorsJPanel", panel);
        java.awt.CardLayout layout = (java.awt.CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageRecordsActionPerformed

    private void populateRequestTable(String requestType) {
        javax.swing.table.DefaultTableModel model =
                new javax.swing.table.DefaultTableModel(
                        new String[]{
                            "ID", "Type", "Status",
                            "Sender", "Receiver", "Date"
                        }, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        if (network != null) {
            for (WorkOrder order :
                    network.getWorkOrderQueue().getWorkOrderList()) {
                if (order instanceof CrossEnterpriseWorkOrder) {
                    CrossEnterpriseWorkOrder request =
                            (CrossEnterpriseWorkOrder) order;
                    if (requestType.equalsIgnoreCase(
                            request.getRequestType())) {
                        model.addRow(new Object[]{
                            request,
                            request.getRequestType(),
                            request.getStatus(),
                            request.getSender(),
                            request.getReceiver(),
                            request.getRequestDate()
                        });
                    }
                }
            }
        }
        tblMain.setModel(model);
    }

    private void showHiringSummary() {
        int candidateRequests = 0;
        int invoices = 0;
        int extensions = 0;
        for (WorkOrder order :
                network.getWorkOrderQueue().getWorkOrderList()) {
            if (order instanceof CrossEnterpriseWorkOrder) {
                String type = ((CrossEnterpriseWorkOrder) order)
                        .getRequestType();
                if ("Candidate Submission".equals(type)) {
                    candidateRequests++;
                } else if ("Client Invoice".equals(type)) {
                    invoices++;
                } else if ("Contract Extension".equals(type)) {
                    extensions++;
                }
            }
        }
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Candidate Submissions: " + candidateRequests
                + "\nClient Invoices: " + invoices
                + "\nContract Extensions: " + extensions,
                "Hiring Manager Summary",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnManageRecords;
    private javax.swing.JButton btnPrimaryAction;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnViewRequests;
    private javax.swing.JButton btnViewRequests1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblMain;
    // End of variables declaration//GEN-END:variables
}
