/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Client;

import Business.Network;
import Core.Enterprise;
import Core.NetworkUtils;
import Core.Organization;
import Core.UserAccount;
import Core.WorkOrder;
import Core.WorkOrderStatus; 
import StaffingAgency.Enums.CandidateStatus;
import StaffingAgency.People.Candidate;
import StaffingAgency.People.Contractor;
import StaffingAgency.Request.CandidateSubmission; 
import StaffingAgency.Request.ContractorAssignment;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class HiringManagerCandidateApprovalJPanel extends javax.swing.JPanel {

    private JPanel container;
    private UserAccount userAccount;
    private Network network;
    private CandidateSubmission selectedRecord;

    private final String[] COLUMN_NAMES = {
        "Work Order ID", "Candidate Name", "Status"
    };

    public HiringManagerCandidateApprovalJPanel(JPanel container, UserAccount userAccount, Network network) {
        initComponents(); 
        this.container = container;
        this.userAccount = userAccount;
        this.network = network;
        refreshTable();
    }

private void refreshTable() {
        DefaultTableModel model = new DefaultTableModel(COLUMN_NAMES, 0) {
            @Override
            public boolean isCellEditable(int row, int col) { return false; }
        };
 
        Organization hrOrg = NetworkUtils.findOrganizationByName(
                network,
                "Client Enterprise",
                "Human Resources Organization"
        );
 
        if (hrOrg != null) {
            for (WorkOrder workOrder : hrOrg.getWorkQueue().getWorkOrderList()) {
                if (workOrder instanceof CandidateSubmission) {
                    CandidateSubmission candidateReq = (CandidateSubmission) workOrder;
 
                    if (candidateReq.getStatus() == WorkOrderStatus.UNDER_REVIEW) {
                        model.addRow(new Object[]{
                            candidateReq, // Or candidateReq.getWorkOrderId()
                            candidateReq.getCandidate().getFullName(),
                            candidateReq.getStatus()
                        });
                    }
                }
            }
        }
        tblData.setModel(model); 
    }

    private void populateForm(CandidateSubmission item) {
        
        txtCandidateName.setText(item.getCandidate().getFullName());
        txtareaResume.setText(item.getCandidate().getSkills());
        txtareaAgencyComments.setText(item.getRecruiterNotes());
    }

    private boolean validateSelection() {
        if (selectedRecord == null) {
            JOptionPane.showMessageDialog(this, "Please select a candidate to review.", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
    
    private void clearFormAndSelection() {
        txtCandidateName.setText("");
        txtareaResume.setText("");
        txtareaAgencyComments.setText("");
        selectedRecord = null;
        tblData.clearSelection();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareaAgencyComments = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtareaResume = new javax.swing.JTextArea();
        txtCandidateName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setText("Agency Comments:");

        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Candidate Approval");

        txtareaAgencyComments.setColumns(20);
        txtareaAgencyComments.setLineWrap(true);
        txtareaAgencyComments.setRows(5);
        txtareaAgencyComments.setEnabled(false);
        jScrollPane2.setViewportView(txtareaAgencyComments);

        jLabel1.setText("Name:");

        txtareaResume.setColumns(20);
        txtareaResume.setLineWrap(true);
        txtareaResume.setRows(5);
        txtareaResume.setEnabled(false);
        jScrollPane3.setViewportView(txtareaResume);

        txtCandidateName.setEnabled(false);

        jLabel3.setText("Resume:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnBack)
                        .addGap(147, 147, 147)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)
                            .addComponent(txtCandidateName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnApprove)
                .addGap(52, 52, 52)
                .addComponent(btnReject)
                .addGap(80, 80, 80)
                .addComponent(btnClear)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCandidateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnApprove)
                            .addComponent(btnReject)
                            .addComponent(btnClear))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        container.remove(this);
        java.awt.CardLayout layout = (java.awt.CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        if (!validateSelection()) return;
 
        Candidate candidate = selectedRecord.getCandidate();
 
        Contractor contractor = new Contractor(
                candidate.getFirstName(),
                candidate.getLastName(),
                candidate.getEmail(),
                candidate.getPhone(),
                candidate.getSkills(),
                new BigDecimal("55.00") // TODO: replace with a real negotiated pay rate
        );
 
        ContractorAssignment assignment = new ContractorAssignment(
                contractor,
                selectedRecord.getStaffingRequest().getStartDate()
        );
 
        selectedRecord.setReceiver(userAccount);
        selectedRecord.linkAssignment(assignment); // also moves status to APPROVED
        candidate.setCandidateStatus(CandidateStatus.PLACED);
 
        // TODO: This is a demo-only stand-in for real account provisioning.
        // Auto-generates a login so the newly hired contractor can actually
        // sign in, since there's no real link between StaffingAgency.People.Contractor
        // and Core.UserAccount/Core.Person yet.
        String baseUsername = (candidate.getFirstName() + "."
                + candidate.getLastName())
                .toLowerCase()
                .replaceAll("[^a-z0-9._-]", "");
 
        String username = baseUsername;
        int suffix = 1;
        while (!network.getUserAccountDirectory().uniqueUsername(username)) {
            username = baseUsername + suffix;
            suffix++;
        }
 
        String defaultPassword = "password";

        Enterprise clientEnterprise = NetworkUtils.findEnterpriseByName(network, "Client Enterprise");

        Core.Person loginPerson;
        if (clientEnterprise != null) {
            loginPerson = clientEnterprise.getPersonDirectory()
                    .createPerson(candidate.getFirstName(), candidate.getLastName());
        } else {
            loginPerson = new Core.Person(candidate.getFirstName(), candidate.getLastName());
        }
        loginPerson.setEmail(candidate.getEmail());
        loginPerson.setPhone(candidate.getPhone());
 
        network.getUserAccountDirectory().createUserAccount(
                username,
                defaultPassword,
                loginPerson,
                new Client.Roles.ContractorRole()
        );
 
        JOptionPane.showMessageDialog(
                this,
                "Candidate approved and converted to a contractor!\n\n"
                + "Login created — username: " + username
                + " / password: " + defaultPassword
        );
        refreshTable();
        clearFormAndSelection();
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        if (!validateSelection()) return;
 
        selectedRecord.setReceiver(userAccount);
        selectedRecord.updateStatus(WorkOrderStatus.REJECTED);
        selectedRecord.getCandidate().setCandidateStatus(CandidateStatus.REJECTED);
 
        JOptionPane.showMessageDialog(this, "Candidate Rejected.");
        refreshTable();
        clearFormAndSelection();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFormAndSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int viewRow = tblData.getSelectedRow();
        if (viewRow >= 0) {
            int modelRow = tblData.convertRowIndexToModel(viewRow);
            selectedRecord = (CandidateSubmission) tblData.getValueAt(modelRow, 0);
            populateForm(selectedRecord);
        }
    }//GEN-LAST:event_tblDataMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtCandidateName;
    private javax.swing.JTextArea txtareaAgencyComments;
    private javax.swing.JTextArea txtareaResume;
    // End of variables declaration//GEN-END:variables
}
