/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Client;

import Business.Network;
import Core.UserAccount;
import UserInterface.WorkArea.*;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author connorewart
 */
public class ProjectSupervisorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorkAreaTemplatePanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Network network;
    public ProjectSupervisorJPanel(JPanel userProcessContainer, UserAccount account, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.network = network;
        //btnViewRequests.setEnabled(true);
        btnBack.setVisible(false);
        //btnReports.setEnabled(true);
        //btnReports.addActionListener(event -> showSupervisorReport());
        populateContractorTable();
    }
    public void setWorkAreaHeader(String title, String subtitle) {
        lblTitle.setText(title);
        lblSubtitle.setText(subtitle);
    }

    public void setButtonLabels(String viewText, String primaryText, String manageText, String reportsText) {
        //btnViewRequests.setText(viewText);
        btnPrimaryAction.setText(primaryText);
        btnManageRecords.setText(manageText);
        //btnReports.setText(reportsText);
    }

    public void clearTable() {
        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) tblMain.getModel();
        model.setRowCount(0);
    }

    public void showMessage(String message) {
        javax.swing.JOptionPane.showMessageDialog(this, message);
    }

    public void showError(String message) {
        javax.swing.JOptionPane.showMessageDialog(this, message, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    private final String[] CONTRACTOR_COLUMNS = {
        "Username", "Full Name", "Role"
    };
    public void populateContractorTable() {
        DefaultTableModel model = new DefaultTableModel(CONTRACTOR_COLUMNS, 0) {};

        if (network != null && network.getUserAccountDirectory() != null) {
            for (UserAccount ua : network.getUserAccountDirectory().getUserAccountList()) {
                if (ua.getSupervisor() != null && ua.getSupervisor().equals(this.account)) {
                    String fullName = (ua.getPerson() != null) ? ua.getPerson().getName() : "N/A";
                    model.addRow(new Object[]{
                        ua,        // Column 0: Stores the UserAccount object (displays username via toString)
                        fullName,  // Column 1: Person's full name
                        ua.getRole() // Column 2: Role
                    });
                }
            }
        }

        tblMain.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        btnManageRecords = new javax.swing.JButton();
        btnPrimaryAction = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 204));

        lblTitle.setFont(new java.awt.Font("Myanmar Sangam MN", 3, 18)); // NOI18N
        lblTitle.setText("Project Supervisor Work Area");

        lblSubtitle.setFont(new java.awt.Font("Myanmar MN", 0, 13)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(102, 102, 102));
        lblSubtitle.setText("Client Enterprise - Operations Organization");

        btnManageRecords.setText("Manage Tasks");
        btnManageRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRecordsActionPerformed(evt);
            }
        });

        btnPrimaryAction.setText("Approve Timecards");
        btnPrimaryAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimaryActionActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.setEnabled(false);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        tblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Type", "Status", "Sender", "Receiver", "Date"
            }
        ));
        jScrollPane1.setViewportView(tblMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblSubtitle)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnManageRecords, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnPrimaryAction, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(lblTitle)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addGap(42, 42, 42)
                .addComponent(btnPrimaryAction)
                .addGap(45, 45, 45)
                .addComponent(btnManageRecords)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnRefresh))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRecordsActionPerformed
        ProjectSupervisorTasksJPanel panel = new ProjectSupervisorTasksJPanel(userProcessContainer, account, network);
        userProcessContainer.add("ProjectSupervisorTasksJPanel", panel);
        java.awt.CardLayout layout = (java.awt.CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageRecordsActionPerformed

    private void btnPrimaryActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimaryActionActionPerformed
        ProjectSupervisorTimecardsJPanel panel = new ProjectSupervisorTimecardsJPanel(userProcessContainer, account, network);
        userProcessContainer.add("ProjectSupervisorTimecardsJPanel", panel);
        java.awt.CardLayout layout = (java.awt.CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPrimaryActionActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateContractorTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void showSupervisorReport() {
        int contractorCount = tblMain.getRowCount();
        int workRequestCount = account == null
                ? 0 : account.getWorkQueue().getWorkOrderList().size();
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Assigned Contractors: " + contractorCount
                + "\nSupervisor Work Requests: " + workRequestCount,
                "Supervisor Summary",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnManageRecords;
    private javax.swing.JButton btnPrimaryAction;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblMain;
    // End of variables declaration//GEN-END:variables
}
