/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.PayrollBilling;

import Business.Network;
import Core.NetworkUtils;
import Core.Organization;
import Core.UserAccount;
import PayrollBilling.ConfigurePayrollBilling;
import PayrollBilling.PayrollBillingModule;
import javax.swing.JPanel;
import PayrollBilling.Record.BillingRecord;
import PayrollBilling.Record.Invoice;
import PayrollBilling.Report.PayrollReport;
import PayrollBilling.Request.BillingRequest;
import StaffingAgency.People.Contractor;
import StaffingAgency.Request.ContractorAssignment;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import UserInterface.WorkArea.*;

/**
 *
 * @author connorewart
 */
public class BillingAnalystWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorkAreaTemplatePanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Network network;
    private PayrollBillingModule module;
    private String currentView;
    
    public BillingAnalystWorkAreaJPanel() {
        initComponents();
    }
    
    public BillingAnalystWorkAreaJPanel(JPanel userProcessContainer,
            UserAccount account,
            Network network) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.network = network;
        this.module = ConfigurePayrollBilling.getSharedPayrollBillingModule();

        setWorkAreaHeader(
                "Billing Analyst Work Area",
                "Payroll & Billing Enterprise - ClientBilling Organization"
        );

        setButtonLabels(
                "Billing Requests",
                "Generate Invoice",
                "Billing Records",
                "Billing Report"
        );

        btnBack.setText("Invoices");
        btnRefresh.setText("Refresh");

        wireButtonActions();
        showBillingRequests();
    }
    
    public void setWorkAreaHeader(String title, String subtitle) {
        lblTitle.setText(title);
        lblSubtitle.setText(subtitle);
    }

    public void setButtonLabels(String viewText, String primaryText, String manageText, String reportsText) {
        btnViewRequests.setText(viewText);
        btnPrimaryAction.setText(primaryText);
        btnManageRecords.setText(manageText);
        btnReports.setText(reportsText);
    }

    public void clearTable() {
        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) tblMain.getModel();
        model.setRowCount(0);
    }

    public void showMessage(String message) {
        javax.swing.JOptionPane.showMessageDialog(this, message);
    }

    public void showError(String message) {
        javax.swing.JOptionPane.showMessageDialog(this, message, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        btnViewRequests = new javax.swing.JButton();
        btnManageRecords = new javax.swing.JButton();
        btnPrimaryAction = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 204));

        lblTitle.setFont(new java.awt.Font("Myanmar Sangam MN", 3, 18)); // NOI18N
        lblTitle.setText("Payroll Specialist Work Area");

        lblSubtitle.setFont(new java.awt.Font("Myanmar MN", 0, 13)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(102, 102, 102));
        lblSubtitle.setText("Payroll & Billing Enterprise - Payroll Processing Organization");

        btnViewRequests.setText("View Request");
        btnViewRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestsActionPerformed(evt);
            }
        });

        btnManageRecords.setText("Manage Records");

        btnPrimaryAction.setText("Primary Action");

        btnBack.setText("Back");

        btnRefresh.setText("Refresh");

        btnReports.setText("Reports");

        tblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Type", "Status", "Sender", "Receiver", "Date"
            }
        ));
        jScrollPane1.setViewportView(tblMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblSubtitle)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnViewRequests)
                                            .addComponent(btnManageRecords))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnPrimaryAction)
                                            .addComponent(btnReports)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblTitle)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewRequests)
                    .addComponent(btnPrimaryAction))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReports)
                    .addComponent(btnManageRecords))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnRefresh))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void wireButtonActions() {
        btnPrimaryAction.addActionListener(e -> generateSelectedInvoice());
        btnManageRecords.addActionListener(e -> showBillingRecords());
        btnReports.addActionListener(e -> showBillingReport());
        btnBack.addActionListener(e -> showInvoices());
        btnRefresh.addActionListener(e -> refreshCurrentView());
    }
    
    private void showBillingRequests() {
        currentView = "requests";

        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Request ID", "Contractor", "Hours", "Status", "Invoice"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (BillingRequest request : module.getBillingRequests()) {
            model.addRow(new Object[]{
                request.getWorkOrderId(),
                contractorName(request.getAssignment()),
                request.getHoursBilled(),
                request.getStatus(),
                request.getInvoice() == null ? "Not Generated" : request.getInvoice().getInvoiceId()
            });
        }

        tblMain.setModel(model);
    }
    
    private void btnViewRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestsActionPerformed
        showBillingRequests();
    }//GEN-LAST:event_btnViewRequestsActionPerformed

    private void generateSelectedInvoice() {
        if (!"requests".equals(currentView)) {
            JOptionPane.showMessageDialog(this, "Please view Billing Requests first.");
            return;
        }

        int row = tblMain.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a billing request first.");
            return;
        }

        Object selectedId = tblMain.getValueAt(row, 0);
        BillingRequest request = findBillingRequestById(selectedId);

        if (request == null) {
            JOptionPane.showMessageDialog(this, "Could not find the selected billing request.");
            return;
        }

        if (request.getInvoice() != null) {
            JOptionPane.showMessageDialog(this, "Invoice has already been generated for this request.");
            return;
        }

        try {
            Invoice invoice = request.processBilling();
            Organization hrOrg = NetworkUtils.findOrganizationByName(
                    network,
                    "Client Enterprise",
                    "Human Resources Organization"
            );

            if (hrOrg != null) {
                hrOrg.getWorkQueue().addWorkOrder(request);
            } else {
                showMessage("Invoice generated locally (HR Organization not found).");
            }
            if (request.getBillingRecord() != null
                    && !module.getBillingRecords().contains(request.getBillingRecord())) {
                module.getBillingRecords().add(request.getBillingRecord());
            }

            if (invoice != null && !module.getInvoices().contains(invoice)) {
                module.getInvoices().add(invoice);
            }

            JOptionPane.showMessageDialog(
                    this,
                    "Invoice generated. Client invoice total: " + money(invoice.getInvoiceTotal())
            );

            showInvoices();

        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage(),
                    "Billing Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void showBillingRecords() {
        currentView = "records";

        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Billing ID", "Contractor", "Hours", "Client Bill Rate", "Client Invoice Total", "Status"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (BillingRecord record : module.getBillingRecords()) {
            model.addRow(new Object[]{
                record.getBillingId(),
                contractorName(record.getAssignment()),
                record.getHoursBilled(),
                money(record.getBillRate()),
                money(record.getInvoiceAmount()),
                record.getBillingStatus()
            });
        }

        tblMain.setModel(model);
    }

    private void showInvoices() {
        currentView = "invoices";

        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Invoice ID", "Timecard ID", "Hours", "Total", "Invoice Date", "Due Date", "Status"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (Invoice invoice : module.getInvoices()) {
            model.addRow(new Object[]{
                invoice.getInvoiceId(),
                invoice.getTimeCardId(),
                invoice.getTotalHours(),
                money(invoice.getInvoiceTotal()),
                invoice.getInvoiceDate(),
                invoice.getDueDate(),
                invoice.getInvoiceStatus()
            });
        }

        tblMain.setModel(model);
    }

    private void showBillingReport() {
        currentView = "report";

        PayrollReport report = new PayrollReport();

        report.generateSummary(
                module.getPayrollRecords(),
                module.getBillingRecords(),
                module.getInvoices(),
                module.getPayrollRequests()
        );

        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Metric", "Value"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        model.addRow(new Object[]{"Total Billing Amount", money(report.getTotalBillingAmount())});
        model.addRow(new Object[]{"Billing Records Processed", report.getBillingRecordsProcessed()});
        model.addRow(new Object[]{"Invoices Generated", report.getInvoicesGenerated()});
        model.addRow(new Object[]{"Total Contractor Hours", report.getTotalContractorHours()});
        model.addRow(new Object[]{"Total Payroll Amount", money(report.getTotalPayrollAmount())});

        tblMain.setModel(model);
    }

    private BillingRequest findBillingRequestById(Object selectedId) {
        if (selectedId == null) {
            return null;
        }

        int requestId;

        try {
            requestId = Integer.parseInt(selectedId.toString());
        } catch (NumberFormatException ex) {
            return null;
        }

        for (BillingRequest request : module.getBillingRequests()) {
            if (request.getWorkOrderId() == requestId) {
                return request;
            }
        }

        return null;
    }

    private void refreshCurrentView() {
        if ("records".equals(currentView)) {
            showBillingRecords();
        } else if ("invoices".equals(currentView)) {
            showInvoices();
        } else if ("report".equals(currentView)) {
            showBillingReport();
        } else {
            showBillingRequests();
        }
    }

    private String contractorName(ContractorAssignment assignment) {
        if (assignment == null) {
            return "N/A";
        }

        Contractor contractor = assignment.getContractor();
        return contractor == null ? "N/A" : contractor.getFullName();
    }

    private String money(BigDecimal amount) {
        return amount == null
                ? "$0.00"
                : "$" + amount.setScale(2, java.math.RoundingMode.HALF_UP).toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnManageRecords;
    private javax.swing.JButton btnPrimaryAction;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnViewRequests;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblMain;
    // End of variables declaration//GEN-END:variables
}
