/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.PayrollBilling;

import StaffingAgency.Request.Contract;
import java.time.LocalDate;
import PayrollBilling.Request.BillingRequest;
import Business.Network;
import Core.NetworkUtils;
import Core.Organization;
import Core.UserAccount;
import Core.WorkOrder;
import Core.WorkOrderStatus;
import Core.WorkOrders.TimecardWorkOrder;
import PayrollBilling.ConfigurePayrollBilling;
import PayrollBilling.PayrollBillingModule;
import PayrollBilling.Record.PaymentRecord;
import PayrollBilling.Record.PayrollRecord;
import PayrollBilling.Report.PayrollReport;
import PayrollBilling.Request.PayrollRequest;
import StaffingAgency.People.Contractor;
import StaffingAgency.Request.ContractorAssignment;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import UserInterface.WorkArea.*;

/**
 *
 * @author connorewart
 */
public class PayrollSpecialistWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorkAreaTemplatePanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Network network;
    private PayrollBillingModule module;
    private String currentView;
    
    
    public PayrollSpecialistWorkAreaJPanel() {
        initComponents();
    }
    
    public PayrollSpecialistWorkAreaJPanel(JPanel userProcessContainer,
            UserAccount account,
            Network network) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.network = network;
        this.module = ConfigurePayrollBilling.getSharedPayrollBillingModule();

        setWorkAreaHeader(
                "Payroll Specialist Work Area",
                "Payroll & Billing Enterprise - PayrollProcessing Organization"
        );

        setButtonLabels(
                "Incoming Timecards",
                "Process Selected",
                "Payroll Records",
                "Payroll Report"
        );

        btnBack.setText("Payment Records");
        btnRefresh.setText("Refresh");

        wireButtonActions();
        showIncomingTimecards();
    }
    
    public void setWorkAreaHeader(String title, String subtitle) {
        lblTitle.setText(title);
        lblSubtitle.setText(subtitle);
    }

    public void setButtonLabels(String viewText, String primaryText, String manageText, String reportsText) {
        btnViewRequests.setText(viewText);
        btnPrimaryAction.setText(primaryText);
        btnManageRecords.setText(manageText);
        btnReports.setText(reportsText);
    }

    public void clearTable() {
        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) tblMain.getModel();
        model.setRowCount(0);
    }

    public void showMessage(String message) {
        javax.swing.JOptionPane.showMessageDialog(this, message);
    }

    public void showError(String message) {
        javax.swing.JOptionPane.showMessageDialog(this, message, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        btnViewRequests = new javax.swing.JButton();
        btnManageRecords = new javax.swing.JButton();
        btnPrimaryAction = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 204));

        lblTitle.setFont(new java.awt.Font("Myanmar Sangam MN", 3, 18)); // NOI18N
        lblTitle.setText("Payroll Specialist Work Area");

        lblSubtitle.setFont(new java.awt.Font("Myanmar MN", 0, 13)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(102, 102, 102));
        lblSubtitle.setText("Payroll & Billing Enterprise - Payroll Processing Organization");

        btnViewRequests.setText("View Request");
        btnViewRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestsActionPerformed(evt);
            }
        });

        btnManageRecords.setText("Manage Records");

        btnPrimaryAction.setText("Primary Action");

        btnBack.setText("Back");

        btnRefresh.setText("Refresh");

        btnReports.setText("Reports");

        tblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Type", "Status", "Sender", "Receiver", "Date"
            }
        ));
        jScrollPane1.setViewportView(tblMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblSubtitle)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnViewRequests)
                                            .addComponent(btnManageRecords))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnPrimaryAction)
                                            .addComponent(btnReports)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblTitle)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewRequests)
                    .addComponent(btnPrimaryAction))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReports)
                    .addComponent(btnManageRecords))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnRefresh))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void wireButtonActions() {
        btnPrimaryAction.addActionListener(e -> processSelected());
        btnManageRecords.addActionListener(e -> showPayrollRecords());
        btnReports.addActionListener(e -> showPayrollReport());
        btnBack.addActionListener(e -> showPaymentRecords());
        btnRefresh.addActionListener(e -> refreshCurrentView());
    }
    
    private void showIncomingTimecards() {
        currentView = "incoming";

        DefaultTableModel model = new DefaultTableModel(
                new String[]{
                    "Timecard ID", "Sender", "Receiver", "Week Ending",
                    "Hours", "Status", "Summary"
                }, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        Organization payrollOrg = getPayrollProcessingOrganization();

        if (payrollOrg != null) {
            for (WorkOrder workOrder : payrollOrg.getWorkQueue().getWorkOrderList()) {
                if (workOrder instanceof TimecardWorkOrder) {
                    TimecardWorkOrder timecard = (TimecardWorkOrder) workOrder;

                    if (timecard.getStatus() == WorkOrderStatus.APPROVED) {
                        model.addRow(new Object[]{
                            timecard,
                            safeUser(timecard.getSender()),
                            safeUser(timecard.getReceiver()),
                            timecard.getWeekEndingDate(),
                            timecard.getTotalHours(),
                            timecard.getStatus(),
                            timecard.getWorkSummary()
                        });
                    }
                }
            }
        }

        tblMain.setModel(model);
    }

    private void showPayrollRecords() {
        currentView = "payrollRecords";

        DefaultTableModel model = new DefaultTableModel(
                new String[]{
                    "Payroll ID", "Contractor", "Hours", "Contractor Pay Rate",
                    "Contractor Pay Total", "Processed Date", "Payment Status"
                }, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (PayrollRecord record : module.getPayrollRecords()) {
            model.addRow(new Object[]{
                record,
                contractorName(record.getAssignment()),
                record.getHoursWorked(),
                money(record.getPayRate()),
                money(record.getTotalAmount()),
                record.getProcessedDate(),
                record.getPaymentStatus()
            });
        }

        tblMain.setModel(model);
    }

    private void showPaymentRecords() {
        currentView = "payments";

        DefaultTableModel model = new DefaultTableModel(
                new String[]{
                    "Payment ID", "Payroll ID", "Contractor",
                    "Amount", "Payment Date", "Status"
                }, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (PaymentRecord record : module.getPaymentRecords()) {
            model.addRow(new Object[]{
                record,
                record.getPayrollRecord() == null ? "N/A" : record.getPayrollRecord().getPayrollId(),
                contractorName(record.getContractor()),
                money(record.getPaymentAmount()),
                record.getPaymentDate(),
                record.getPaymentStatus()
            });
        }

        tblMain.setModel(model);
    }

    private void showPayrollReport() {
        currentView = "report";

        PayrollReport report = new PayrollReport();

        report.generateSummary(
                module.getPayrollRecords(),
                module.getBillingRecords(),
                module.getInvoices(),
                module.getPayrollRequests()
        );

        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Metric", "Value"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        model.addRow(new Object[]{"Total Contractor Hours", report.getTotalContractorHours()});
        model.addRow(new Object[]{"Total Payroll Amount", money(report.getTotalPayrollAmount())});
        model.addRow(new Object[]{"Total Billing Amount", money(report.getTotalBillingAmount())});
        model.addRow(new Object[]{"Payroll Records Processed", report.getPayrollRecordsProcessed()});
        model.addRow(new Object[]{"Billing Records Processed", report.getBillingRecordsProcessed()});
        model.addRow(new Object[]{"Invoices Generated", report.getInvoicesGenerated()});
        model.addRow(new Object[]{"Pending Payroll Requests", report.getPendingPayrollRequests()});

        tblMain.setModel(model);
    }
    
    private void processSelected() {
        int row = tblMain.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a timecard first.");
            return;
        }

        Object selected = tblMain.getValueAt(row, 0);

        if (!(selected instanceof TimecardWorkOrder)) {
            JOptionPane.showMessageDialog(this, "Select an incoming timecard to process payroll.");
            return;
        }

        processTimecard((TimecardWorkOrder) selected);
    }

    private void processTimecard(TimecardWorkOrder timecard) {
        if (timecard == null) {
            JOptionPane.showMessageDialog(this, "No timecard selected.");
            return;
        }

        if (timecard.getTotalHours() <= 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "This timecard has 0 hours and cannot be processed for payroll. "
                    + "Please have the contractor submit hours before processing.",
                    "Invalid Timecard",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        ContractorAssignment assignment = getAssignmentForTimecard(timecard);

        if (assignment == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No contractor assignment is available yet, so payroll cannot calculate a pay rate.",
                    "Missing Assignment",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        try {
            PayrollRequest payrollRequest = new PayrollRequest(timecard, assignment);
            payrollRequest.setSender(timecard.getSender());
            payrollRequest.setReceiver(account);

            PayrollRecord payrollRecord = payrollRequest.processPayroll();
            PaymentRecord paymentRecord = new PaymentRecord(payrollRecord);

            timecard.setStatus(WorkOrderStatus.COMPLETED);

            module.getPayrollRequests().add(payrollRequest);
            module.getPayrollRecords().add(payrollRecord);
            module.getPaymentRecords().add(paymentRecord);
            
            BillingRequest billingRequest = new BillingRequest(timecard, assignment);
            billingRequest.setSender(account);
            billingRequest.setReceiver(getBillingAnalystAccount());

            module.getBillingRequests().add(billingRequest);

            Organization billingOrg = getClientBillingOrganization();

            if (billingOrg != null) {
                billingOrg.getWorkQueue().getWorkOrderList().add(billingRequest);
            }

            JOptionPane.showMessageDialog(
                    this,
                    "Payroll processed. Contractor payment total: " + money(payrollRecord.getTotalAmount())
            );

            showPayrollRecords();

        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage(),
                    "Payroll Processing Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    private void btnViewRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestsActionPerformed
        showIncomingTimecards();
    }//GEN-LAST:event_btnViewRequestsActionPerformed

    private Organization getPayrollProcessingOrganization() {
        return NetworkUtils.findOrganizationByName(
                network,
                "Payroll and Billing Enterprise",
                "PayrollProcessing"
        );
    }
    
    private Organization getClientBillingOrganization() {
        return NetworkUtils.findOrganizationByName(
                network,
                "Payroll and Billing Enterprise",
                "ClientBilling"
        );
    }
    
    private UserAccount getBillingAnalystAccount() {
        if (network == null || network.getUserAccountDirectory() == null) {
            return null;
        }

        return network.getUserAccountDirectory().authenticateUser(
                "b.analyst",
                "password"
        );
    }
    
    private ContractorAssignment getAssignmentForTimecard(
        TimecardWorkOrder timecard) {

    if (timecard == null
            || timecard.getSender() == null
            || timecard.getSender().getPerson() == null) {
        return null;
    }

    String contractorName =
            timecard.getSender().getPerson().getName();

    // Reuse an assignment previously created for this contractor.
    for (PayrollRequest request : module.getPayrollRequests()) {
        ContractorAssignment existing = request.getAssignment();

        if (existing != null
                && existing.getContractor() != null
                && contractorName.equalsIgnoreCase(
                        existing.getContractor().getFullName())) {
            return existing;
        }
    }

    /*
     * The current TimecardWorkOrder does not carry its own
     * ContractorAssignment. Use the sample contract only as
     * the source of the pay and billing rates.
     */
    ContractorAssignment template = getDemoAssignment();

    if (template == null || template.getContract() == null) {
        return null;
    }

    String firstName =
            timecard.getSender().getPerson().getFirstName();
    String lastName =
            timecard.getSender().getPerson().getLastName();

    if (firstName == null || firstName.isBlank()) {
        firstName = timecard.getSender().getUsername();
    }

    if (lastName == null || lastName.isBlank()) {
        lastName = "Contractor";
    }

    String emailPrefix = timecard.getSender()
            .getUsername()
            .replaceAll("[^A-Za-z0-9._-]", "")
            .toLowerCase();

    if (emailPrefix.isBlank()) {
        emailPrefix = "contractor";
    }

    Contract templateContract = template.getContract();

    Contractor contractor = new Contractor(
            firstName,
            lastName,
            emailPrefix + "@example.com",
            "555-010-0000",
            "Assigned contractor",
            templateContract.getPayRate()
    );

    LocalDate startDate =
            timecard.getWeekEndingDate() == null
                    ? LocalDate.now()
                    : timecard.getWeekEndingDate().minusDays(6);

    ContractorAssignment assignment =
            new ContractorAssignment(contractor, startDate);

    new Contract(
            assignment,
            startDate,
            startDate.plusMonths(3),
            templateContract.getPayRate(),
            templateContract.getBillRate()
    );

    return assignment;
}

    private ContractorAssignment getDemoAssignment() {
        if (module == null || module.getPayrollRequests().isEmpty()) {
            return null;
        }

        return module.getPayrollRequests().get(0).getAssignment();
    }

    private void refreshCurrentView() {
        if ("payrollRecords".equals(currentView)) {
            showPayrollRecords();
        } else if ("payments".equals(currentView)) {
            showPaymentRecords();
        } else if ("report".equals(currentView)) {
            showPayrollReport();
        } else {
            showIncomingTimecards();
        }
    }

    private String safeUser(UserAccount userAccount) {
        return userAccount == null ? "N/A" : userAccount.getUsername();
    }

    private String contractorName(ContractorAssignment assignment) {
        if (assignment == null) {
            return "N/A";
        }

        return contractorName(assignment.getContractor());
    }

    private String contractorName(Contractor contractor) {
        return contractor == null ? "N/A" : contractor.getFullName();
    }

    private String money(BigDecimal amount) {
        return amount == null
                ? "$0.00"
                : "$" + amount.setScale(2, java.math.RoundingMode.HALF_UP).toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnManageRecords;
    private javax.swing.JButton btnPrimaryAction;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnViewRequests;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblMain;
    // End of variables declaration//GEN-END:variables
}
